### ISSUE TITLE
Level Up Your Database Fu

### ISSUE THREAD

**Issue by barrettclark** [rubyftw/rubyftw.github.io#18]
### Talk Description

Something about databases and SQL.  ActiveRecord is helpful and all, but SQL and Postgres can rock your face off.

### Dates Available

*

**Comment by philtr** [comment]
:+1:

When would you be available?

**Comment by barrettclark** [comment]
We have something on the calendar for 2/24.  How does March (3/24) look?

**Comment by philtr** [comment]
March is great! I'lol get it on the calendar
