### ISSUE TITLE
Meetup Event importer

### ISSUE THREAD

**Issue by philtr** [rubyftw/rubyftw.github.io#24]
Would love to have a script that does a few things. It could be one script or separate ones.
1. Grab upcoming events from the Meetup API and stuff them in Jekyll posts
   - It looks like venue data comes back from the API as well, so that could be nice. (You can construct a Google maps link from an address)
   - The description comes back as HTML—it would be awesome if we could convert it to markdown
   - Don't create duplicate events. Maybe store the Meetup event ID in the yaml frontmatter?
2. Move past events to the `_archived_events` folder

**Comment by antwonlee** [comment]
@philtr I am not sure how Meetup API events can trigger to create Jekyll post files within remote github repo with proper file names.  Perhaps, I didn't fully understand the description.

What was your initial approach?  Were you just wanting some kind of bash script for your local machine?

**Comment by philtr** [comment]
Yeah, something like that. I wasn't thinking automatically necessarily, but some way to automate the 5 minutes a month it takes me to update the site 😜

Ideally it would be implemented as a Jekyll command, e.g. `jekyll meetup --token API_KEY`

Here's one that I use to deploy my site: https://github.com/spatula/phillipridlen/blob/master/_gems/jekyll-deploy/lib/jekyll/deploy.rb

I keep meaning to get around to doing this myself, but I never have gotten around to it. If you don't want to do this, another thing we need is some kind of Slack inviter. We could probably use the Heroku free tier for that.

**Comment by fregas** [comment]
there are open source slack inviters out there.

**Comment by philtr** [comment]
@fregas — Yeah, that's what I was thinking. A couple I'm aware of:

- https://github.com/rauchg/slackin
- https://github.com/outsideris/slack-invite-automation

There are probably others as well

**Comment by philtr** [comment]
Moved the discussion about the Slack Inviter to #26.

**Comment by antwonlee** [comment]
I could help set up Slackin, but don't have access to our groups's slack account.

**Comment by antwonlee** [comment]
@philtr Another approach can be just parsing the data from MeetUp API and displaying the most recent event in the HTML component from the current Jekyll site.

Is there a reason why you archive each posts in Jekyll?  If site's sole reason is to display most current updates from the MeetUp content, then you can post details in MeetUp one time and not worry about writing posts each time in Jekyll whenever there is a new MeetUp.  Just thinking out loud here, unless you want to archive each posts?

**Comment by philtr** [comment]
I do like having the archive of each post, as well as showing all planned upcoming events. We're not currently displaying archived events anywhere other than here http://rubyftw.org/events/archive.json. 

We also can't fetch events from the JavaScript, because then it will expose private API keys for Meetup. I'm not 100% opposed to converting the site to be dynamic, but I am strongly against it.

**Comment by antwonlee** [comment]
@philtr Right on.  I will take a stab at this when I have some spare time if my :baby: allows—hopefully to save you some time :+1:

**Comment by antwonlee** [comment]
I am 95% done with this ruby script.  Do you want me to fork, new branch, push then do a pull request?  I am not sure how you do the contribution process. 

Since RubyFTW's MeetUp events are private to admins only, I couldn't access the data with my API key.  So I did a demo with public MeetUp event records from https://www.meetup.com/ny-tech/.  

When you run the ruby script, you will just need to put your secret key as an environment variable and uncomment the RubyFTW MeetUp url.  You can run the script by `ruby meetup.rb`

It has a simple method where you can choose to (or not to) archive all the files from `_upcoming_events` directory to `_archive_events`.  Unfortunately, it doesn't iterate through each files and give you the option to chose per file.  Perhaps you can add that later.

It's a rough copy, perhaps you can refactor and make it better.

**Comment by antwonlee** [comment]
The reason why I wasn't able to get data was because non of the events are `upcoming`.   If you add `status=past` you can get all the past events.  

`https://api.meetup.com/2/events?key=#{meetup_api_key}&group_urlname=#{meetup_group_url}&sign=true&status=past`
