### ISSUE TITLE
Slack Inviter

### ISSUE THREAD

**Issue by philtr** [rubyftw/rubyftw.github.io#26]
Continuing the discussion from #24.

We need an easy way for folks to sign up for Slack. There are several open source inviters that we could run on the Heroku free tier. A couple I'm aware of:

- https://github.com/rauchg/slackin
- https://github.com/outsideris/slack-invite-automation

Once we have it up and running, we need to update the Slack link in the footer to point to the inviter.

**Comment by antwonlee** [comment]
It will be nice to perhaps integrate github with group's slack as well.   I vote `slackin`

**Comment by philtr** [comment]
Oh great idea! I just added a #github channel if you want to join!

**Comment by antwonlee** [comment]
:+1:

**Comment by philtr** [comment]
> I could help set up Slackin, but don't have access to our groups's slack account.

I don't either—@davidray will either need to give you a token or make you an admin. (Maybe he can make me one while he's at it 😁)

**Comment by philtr** [comment]
http://rubyftw-slackin.herokuapp.com
